package com.onz.modules.review.web.dto;

import com.onz.common.enums.YN;
import com.onz.common.web.BaseApiController;
import com.onz.modules.review.domain.dto.ReviewAll;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@NoArgsConstructor
public class ReviewResponseDto extends BaseApiController {
    private String Type;
    private Long id;
    private YN isDelete;
    private String ModifiedAt;
    private String state;
    private String CreatedAt;
    private YN WorkExpOpenYn;
    private String item_1;
    private YN item_2;
    private YN item_3;
    private String item_4;
    private String item_5;
    private YN item_6;
    private Long CompanyId;
    private Long AccountId;
    private String txtAdmin;
    private Long workExp;
    private String Zonecode;
    private Long amt;
    private Long amtOld;
    private String apprDt;
    private String apprId;
    private String apprTxt;
    private String endAtmYn;
    private String etcAmt;
    private String etcItems;
    private String etcYn;
    private String mapsidogunguName;
    private String topchoiceDt;
    private YN topchoiceYn;
    private YN annYn;
    private String image1;
    private String image2;
    private String image3;
    private String image4;
    private String image5;
    private String item_b1;
    private String item_b2;
    private String item_b3;
    private String item_c1;
    private String item_c2;
    private String item_c3;
    private String item_d1;
    private String item_d2;
    private String q_1;
    private String likeCode;
    private String Txt;

    private String impCost;
    private String workCost;
    private String addCost;
    private String etcCost;
    private Long totalCost;

    public ReviewResponseDto(ReviewAll reviewAll) {
        this.Type =reviewAll.getType();
        this.id = reviewAll.getId();
        this.isDelete = reviewAll.getis_delete();
        this.ModifiedAt = reviewAll.getmodified_at();
        this.state = reviewAll.getstate();
        this.CreatedAt = reviewAll.getCreated_at();
        this.WorkExpOpenYn = reviewAll.getwork_exp_open_yn();
        this.item_1 = reviewAll.getItem_1();
        this.item_2 = reviewAll.getItem_2();
        this.item_3 = reviewAll.getItem_3();
        this.item_4 = reviewAll.getItem_4();
        this.item_5 = reviewAll.getItem_5();
        this.item_6 = reviewAll.getItem_6();
        this.q_1=reviewAll.gettopQ1();
        this.CompanyId = reviewAll.getcompany_id();
        this.AccountId = reviewAll.getaccount_id();
        this.txtAdmin = reviewAll.gettxt_admin();
        this.workExp = reviewAll.getwork_exp();
        this.Zonecode = reviewAll.getZonecode();
        this.amt = reviewAll.getamt();
        this.amtOld = reviewAll.getamt_old();
        this.apprDt = reviewAll.getappr_dt();
        this.apprId = reviewAll.getappr_id();
        this.apprTxt = reviewAll.getappr_txt();
        this.endAtmYn = reviewAll.getend_atm_yn();
        this.etcAmt = reviewAll.getetc_amt();
        this.etcItems = reviewAll.getetc_items();
        this.etcYn = reviewAll.getetc_yn();
        this.mapsidogunguName = reviewAll.getmapsidogungu_name();
        this.topchoiceDt = reviewAll.gettopchoice_dt();
        this.topchoiceYn = reviewAll.gettopchoice_yn();
        this.annYn = reviewAll.getann_yn();
        this.image1 = reviewAll.getimage1();
        this.image2 = reviewAll.getimage2();
        this.image3 = reviewAll.getimage3();
        this.image4 = reviewAll.getimage4();
        this.image5 = reviewAll.getimage5();
        this.item_b1 = reviewAll.getitem_b1();
        this.item_b2 = reviewAll.getitem_b2();
        this.item_b3 = reviewAll.getitem_b3();
        this.item_c1 = reviewAll.getitem_c1();
        this.item_c2 = reviewAll.getitem_c2();
        this.item_c3 = reviewAll.getitem_c3();
        this.item_d1 = reviewAll.getitem_d1();
        this.item_d2 = reviewAll.getitem_d2();
        this.likeCode = reviewAll.getlike_code();
        this.Txt = reviewAll.getTxt();
        this.impCost = reviewAll.getimpCost();
        this.workCost = reviewAll.getworkCost();
        this.addCost = reviewAll.getaddCost();
        this.etcCost = reviewAll.getetcCost();
        this.totalCost = reviewAll.gettotalCost();
    }
}